---

  - name: Read rsyslog file
    command: cat /etc/rsyslog.conf
    register: catoutput
    changed_when: false

  - name: Add rule if not present
    lineinfile:
      path: /etc/rsyslog.conf
      line: auth.* action(type="omfwd" target="{{haproxy_lb_ip}}" port="{{rsyslog_port}}" protocol="tcp" action.resumeRetryCount="{{retry_count_value}}" queue.type="{{queue_type_value}}" queue.size="{{queue_size_value}}")
    when:
      - catoutput.stdout.find('auth.*') == -1
    notify:
      - restart rsyslog

  - name: Update content rule if already present
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^(.*)action.resumeRetryCount(.*)$'
      line: auth.* action(type="omfwd" target="{{haproxy_lb_ip}}" port="{{rsyslog_port}}" protocol="tcp" action.resumeRetryCount="{{retry_count_value}}" queue.type="{{queue_type_value}}" queue.size="{{queue_size_value}}")
    when:
      - catoutput.stdout.find('auth.*') == 0
    notify:
      - restart rsyslog
